// To use ipcRenderer in a project generated by create-react-app
// https://github.com/electron/electron/issues/9920

declare global {
  interface Window {
    ipcRenderer: IpcRenderer;
  }
}

export interface IpcRenderer {
  invoke(channel: string, ...args: any[]): Promise<any>;
  send(channel: string, ...args: any[]): void;

  /** @return A function that removes this listener. */
  on(channel: string, listener: (...args: any[]) => void): () => void;
}
